### PR TITLE
docker support

### PR DESCRIPTION
**Pull request by sridhar0605**
Hi @EricKutschera ,

Thank you for this much awaited update.
Added docker support with minimal install. 
I did not add PAIRADISE  to this image reason being conda.
conda init looks for bash that will enable conda activate. That is viable only if we have a login bash shell, not trivial but happy to spend some more time later if need be.

I added samtools and some other python (go to) modules, feel free to drop them incase you want a slimmer image. Was able to test docker image using this `docker pull sridnona/rmats_turbo_4.1.0:v2` on GCP.

Thanks
Sid

### CODE REVIEW

**Comment by EricKutschera** [comment]
Hi Sid,

Thanks for sharing this Dockerfile. I'm not super familiar with docker myself, but this looks very reasonable to me.

I'd like to spend some time getting familiar with docker before adding an official Dockerfile to the repo. In the meantime, we can leave this pull request open so that other rMATS users can make use of your work, if that's ok with you.

**Comment by sridhar0605** [comment]
Sure thing!

**Comment by yxing77** [comment]
Thanks for the effort! What's the bottleneck for adding PAIRADISE to the docker image, and is there a way to get around it?

**Comment by sridhar0605** [comment]
@yxing77 Have not thought about it yet but this is on my mind, [multi_stage_build](https://docs.docker.com/develop/develop-images/multistage-build/) in case this cannot be built in one single image. We can build PAIRADISE in a separate image if it gets too cumbersome.

Will take a dig at it soon. 

Thanks
Sid

**Comment by EricKutschera** [comment]
I added a Dockerfile in this commit: https://github.com/Xinglab/rmats-turbo/commit/eea56cfef9cb2436ac11ba8d5ddbd53df0168f99 with the image available at https://hub.docker.com/r/xinglab/rmats

The Dockerfile installs PAIRADISE without using conda to avoid the issue that you pointed out of needing a login bash shell. I tried to keep the image minimal, and people can add to it to fit their use case.

**Pull request closed without merging**
